" vim: fdm=marker isk-==
" because sometime you make mistakes:
" set debug=msg

set nocp
set rtp+=~/.vim/pathogen
call pathogen#infect()

set aw
nnoremap ,x :make<cr>

" :h 'lz' for help on lz
" and so on ...
" as summary, my vim is
" (nocp) not compatible with vi
" (vb)  don't beep (screen flash instead)
" (lz)  don't refresh when busy with macros
" (hid) don't abandon buffers
" (ai)  autoindent
" (lbr) don't wrap in a middle of a word
" (so)  cursor try to stay at the middle of the screen
" (ul)  you can undo ... x times
" (wim) command line completion show you a list
"       and let you decide
" (ff)  gain 1 octet by line ;)
" (ml)  honor modlines (vim: configuration in the current file)
" (is)  next match for the RE you're typing
" (hls) all matches of the last RE

set nocp vb lz ai lbr ml hid hls is
set sw=4 ul=1000 wim=longest,list so=999 ff=unix dy=uhex

" no timeout for mapping sequences
set notimeout nottimeout
" always want status bar
set laststatus=2
set spf=~/.vim/spell/mine.latin1.add
" "set statusline=%F%m%r%h%w\ [ff=%{&ff},ft=%Y][ascii=\%03.3b,hex=\%02.2B](y=%04l,vx=%04v)
set dictionary+=~/.vim/dicts/tt2,~/.vim/dicts/html

syn on
filetype on
filetype indent plugin on

" lovely long parentheses indent in C too :)
set cino=(s,m1


com -complete=custom,ListUsers -nargs=1 Shoot :wincmd new|<args>
fun ListUsers(A,L,P)
    return system("cat ~/.vim/rt/users")
endfun

nnoremap ,m :let @/='X'<cr><c-w><c-n>:setf mail<cr>:0r~/.vim/mutt_drafts/

com!  -complete=filetype -nargs=1 Sp wincmd n | setf <args>
com!  -nargs=0 VT lcd ~/todo |e today

set colorcolumn=80

" i said: i *WANT* to edit this file!
nnoremap ,gf :echo system("mkdir -p ".expand('<cfile>:h'))<cr>:e <cfile><cr>

" on my laptop, the <esc> key passed away... so i need a hack

map! ² <esc>
imap ² <esc>

" try to avoid typing <cr> after commands
" still need to investigate, type :h hit-<tab>
set shm=at ch=3

" DiffHead makes a vimdiff between the current version of a file and the one
" commited in HEAD so you can split changes into atomic commits
"
" * edit % and save it with w|!g add %
" * remove %~ after work

command -bang DiffHead w<bang> %~
    \| exec "%!g show HEAD:%"
    \| diffthis | vsplit %~ | diffthis

" current experiments {{{

" on emailing
command -range=% FEmail <line1>,<line2>y|enew|setf emails|set bt=nofile|0put|%!matches_email
command! -range Display <line1>,<line2>!xargs luds by mail|luds/+ 'disp.*'

" on editing ldap entries
command LDAPeditor vsplit|lcd ~/ldapeditor
" }}}

" syntastic {{{

" recommended configuration made by
" https://github.com/scrooloose/syntastic#settings

" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
" 
" let g:syntastic_always_populate_loc_list = 1
" let g:syntastic_auto_loc_list = 1
" let g:syntastic_check_on_open = 1
" let g:syntastic_check_on_wq = 0
" 
" " my way
" 
" let g:syntastic_python_python_exec = '/usr/bin/python3'

" }}}

